CREATE DATABASE IF NOT EXISTS sqlhelper;

use sqlhelper

CREATE TABLE IF NOT EXISTS DatabaseManagement (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATABASE_NAME VARCHAR(255) NOT NULL UNIQUE,
    SYSTEM_NAME VARCHAR(255) NOT NULL UNIQUE,
    CREATOR VARCHAR(255) NOT NULL DEFAULT 'KILLIAN',
    CREATED VARCHAR(11) NOT NULL ,
    DESCRIPTION VARCHAR(255) ,
    SURF VARCHAR(255) NOT NULL,
    SOFTWARE VARCHAR(255) NOT NULL DEFAULT 'MYSQL',
    UPDATED VARCHAR(11) NOT NULL 
);


CREATE TABLE IF NOT EXISTS TableManagement (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATABASE_ID INT NOT NULL,
    TABLE_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    CREATOR VARCHAR(255) NOT NULL DEFAULT 'KILLIAN',
    CREATED VARCHAR(11) NOT NULL ,
    UPDATED VARCHAR(11) NOT NULL, 
    STATUS VARCHAR(10) NOT NULL,
    UNIQUE(DATABASE_ID, TABLE_NAME)
);

CREATE TABLE IF NOT EXISTS FieldManagement (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATABASE_ID INT NOT NULL,
    TABLE_ID INT NOT NULL,
    FIELD_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) ,
    TYPE VARCHAR(50) NOT NULL ,
    LENGTH INT,
    CREATOR VARCHAR(255) NOT NULL DEFAULT 'KILLIAN',
    CREATED VARCHAR(11) NOT NULL ,
    UPDATED VARCHAR(11) NOT NULL, 
    ISNULL ENUM('Y', 'N') NOT NULL,
    ISKEY ENUM('PRIMARY', 'FOREIGN', 'UNIQUE', '') DEFAULT '',
    DEFAULT_VALUE VARCHAR(50),
    UNIQUE(TABLE_ID, FIELD_NAME)
)